services:

  postgres:
    image: postgres:16

    container_name: ibge_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ibge_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - ibge_network

  pgadmin:
    image: dpage/pgadmin4

    container_name: ibge_pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8080:80"

    depends_on:
      - postgres

    networks:
      - ibge_network

  jupyter:
    build: .

    container_name: ibge_jupyter

    restart: always

    ports:
      - "8888:8888"

    volumes:
      - ./:/home/jovyan/work 

    working_dir: /home/jovyan/work

    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ibge
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/ibge_db

    depends_on:
      - postgres

    networks:
      - ibge_network

  pipeline:
    build: .

    container_name: ibge_pipeline

    profiles:
      - pipeline

    volumes:
      - ./:/home/jovyan/work

    working_dir: /home/jovyan/work

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/ibge_db

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - ibge_network

    command: python -m src.pipeline

networks:
  ibge_network:

volumes:
  postgres_data:
